### ISSUE TITLE
Icebullet selectable on the water

### ISSUE THREAD

**Issue by Legendary-Ocean** [ProjectKorra/ProjectKorra#1284]
When I set the Dynamic Sourcing setting of the water to false, the ice bullet becomes selectable with water. It leaves gaps in the water. pk reload fixes these spaces.

![224490207-def44723-eb11-43c4-a2dd-db76dfaaac96](https://user-images.githubusercontent.com/83317642/228651442-81a6d201-4de8-42a3-a641-7711e08d8c71.png)

**Comment by Dreig-PSD** [comment]
(fixed in 1.12 PR)

**Comment by Legendary-Ocean** [comment]
Now, if I click shift while looking at snow or water, iceblast goes directly to cooldown. works normally for ice source.

my config settings:

```
  Water:
    DynamicSourcing: false
```

```
    IceBlast:
      Enabled: true
      Damage: 3
      Range: 30
      DeflectRange: 3
      CollisionRadius: 1
      Interval: 0
      Cooldown: 4500
      AllowSnow: true
```

**Comment by StrangeOne101** [comment]
Can you confirm this still happens on 1.113?

**Comment by Legendary-Ocean** [comment]
> Can you confirm this still happens on 1.113?

yes

![2024-05-13_18 00 05](https://github.com/ProjectKorra/ProjectKorra/assets/83317642/fe5816a0-5aaf-450b-b8de-97f53974ca59)

**Comment by Legendary-Ocean** [comment]
By the way this problem still exists. A friend of mine who wants dynamic source to be disabled has holes in all the lakes in the arena on his server, because of iceblast. I told them that if they opened dynamic source it would be fixed but they didn't listen to me. There are holes in all the water. I am doing /pk reload to make it go away.

> Spigot version: 1.20.4
> Core Version: 1.12.0-BETA-13
